workflows:
  ios-app:
    name: Build iOS App
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "swift_app.xcworkspace"
        XCODE_SCHEME: "swift_app"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          brew install swiftlint
          gem install cocoapods
      - name: Create Xcode Project
        script: |
          mkdir MyApp
          cd MyApp
          swift package init --type executable
          swift package describe
      - name: Build iOS app
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE \
                     -scheme $XCODE_SCHEME \
                     -sdk iphoneos \
                     -configuration Release \
                     build CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" PROVISIONING_PROFILE_SPECIFIER=""
    artifacts:
      - build/ios/iphoneos/*.ipa
